### ISSUE TITLE
Custom Adjustments do not work with customer_option type

### ISSUE THREAD

**Issue by seizan8** [Brille24/SyliusCustomOptionsPlugin#106]
I created a Subscriber like in the "Creating a custom adjustment" chapter. However, if I'm using CustomerOptionRecalculator::CUSTOMER_OPTION_ADJUSTMENT as type then my adjustments are not saved to the DB. They do get added in my subscriber. Just somehow they get removed again, I guess. And hence never make it to the DB.

As soon as I use my own type tho Booom! They are saved. 

Plugin version 2.14.1

**Comment by mamazu** [comment]
Thanks for reporting this bug. I will try to get to it in the upcoming days.

**Comment by seizan8** [comment]
Thanks! I tried to look into it and couldn't figure out how it happens. Didn't understand what is happening after I add the Adjustment.

**Comment by mamazu** [comment]
Do you have steps on how to reproduce that error? I have just added the `GiftcardSubscriber` to the project and added a gift card customer option to a product. And it works, if I put a product in the cart with it, then it saves it to the database.

**Comment by seizan8** [comment]
hmmmm. It seems to work now.

I did clear the cache multiple times when I had said issue. Not sure why that happened. I guess it was just some weird coincidence on my end.
