### ISSUE TITLE
Customer option File resume to "This value is not valid"

### ISSUE THREAD

**Issue by Loocos** [Brille24/SyliusCustomOptionsPlugin#114]
Hi there,

I'm wondering if you guys have also the same error when adding a product to cart with customer option (File type) with Sylius >= v1.10
it say a form error : The value is not valid.

I was able to fix it by replacing this line in Form\product_theme.html.twig : 
`<input type="hidden" name="{{full_name ~ '[data]' }}" id="{{ id ~ '_data'}}" />`
To
`<input type="hidden" name="{{full_name }}" id="{{ id ~ '_data'}}" />`

If yes, I will do a PR to fix it.
Thanks for your feedback :)

**Comment by mamazu** [comment]
That's a good question. Currently we are only using this plugin in a headless mode but one of our developers can have a look at it. @JakobTolkemit

**Comment by jeromin** [comment]
Hi and thanks @Loocos for the tips but did you figured it out when the file option is mean to be required ?

Symfony Form absolutely wants to validate the file input (`The value is not valid`) as it is an array [ data => imgFile... ])
whereas CustomOptionPlugin validates the requirement (`brille24.form.customer_options.required`) but it is incompatible with setting the same input name.

**Comment by mamazu** [comment]
I think I found the issue. Could you check the pull request #128 ? This should fix the validation for files.
