### ISSUE TITLE
Compatibility with Sylius 1.12

### ISSUE THREAD

**Issue by Prometee** [Brille24/SyliusCustomOptionsPlugin#116]
Hello,

While testing this plugin with `sylius/sylius-standard:1.12.x-dev`, I was unable to install it because of the strict restriction of this plugin `composer.json` file.

**Solution :**

Remove the strict requirements for Sylius and replace it by : `^1.9`

Also it's maybe useless to specify the php version inside a plugin unless there is a specific reason because Sylius is already requiring a specific PHP version.

Finally, the requirement to `symfony/event-dispatcher` is a duplicate because Sylius already need it : `composer why symfony/event-dispatcher`

**Comment by mamazu** [comment]
Thanks a lot for contributing the update to the project.
