### ISSUE TITLE
Using plugin with attributes

### ISSUE THREAD

**Issue by cwa-cc** [Brille24/SyliusCustomOptionsPlugin#136]
Hi, 

Can you please confirm me that the plugin doesn't work with attributes in the entities ?

Think in advance.

**Comment by mamazu** [comment]
Yes, this plugin uses the doctrine XML Configuration for entities. But I am more than happy to merge a PR if you want to switch the entities over to attributes.

**Comment by cwa-cc** [comment]
Oh yes please 👍

Thanks so much, because I'm using (and maybe more people) attributes ...

**Comment by mamazu** [comment]
We are already in the process of updating our plugins, if you have time and can contribute yourself, that would be much appreciated.

**Comment by cwa-cc** [comment]
Hi @mamazu,
I come back to you to know if the plugin already works with attributes in the entities ?
Thanks for your reply
Have a good day

**Comment by mamazu** [comment]
I'm sorry to tell you that we haven't had the time to work on this.

**Comment by cwa-cc** [comment]
And do you think that you will do soon ?
If not, can you please tell me what I need to do exactly to use the attributes ?
Thanks in advance
Have a nice day

**Comment by mamazu** [comment]
As far as I know, you only have to take a look at the attributes that are currently located under `src/Resources/config/doctrine/`  and add their respective counter parts to the Entities in the `src/Entities` directory.

**Comment by mamazu** [comment]
Closing this as the latest version actually does support attributes now. :tada:
