### ISSUE TITLE
simplexml_load_string

### ISSUE THREAD

**Issue by kabasonic** [Brille24/SyliusCustomOptionsPlugin#141]
Please fix the src/Resources/config/doctrine/CustomerOptions.Validator.Condition.orm.xml  for version 3.0.2, there is a wrong tag during closing. It's fine on the master branch, but not for the version.
`
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping">
    <mapped-superclass
            name="Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\Validator\Condition"
            table="brille24_customer_option_group_validator_condition"
    >
      ....
    </entity>
</doctrine-mapping>`

**Comment by JakobTolkemit** [comment]
I just tagged the master as 3.0.3
