### ISSUE TITLE
Conflict with doctrine/dbal ^3.0 on Sylius 1.12.11

### ISSUE THREAD

**Issue by MichaNeroucheff** [Brille24/SyliusCustomOptionsPlugin#144]
Hello,

I try to install your options plugin on a fresh new Sylius 1.12.11 but it's seems there is a conflict with doctrine dbal.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - brille24/sylius-customer-options-plugin[v3.0.0, ..., v3.0.3] conflict with doctrine/dbal ^3.0.
    - sylius/sylius v1.12.11 requires doctrine/dbal ^2.7 || ^3.0 -> satisfiable by doctrine/dbal[3.7.1].
    - sylius/sylius is locked to version v1.12.11 and an update of this package was not requested.
    - Root composer.json requires brille24/sylius-customer-options-plugin ^3.0 -> satisfiable by brille24/sylius-customer-options-plugin[v3.0.0, v3.0.1, v3.0.2, v3.0.3].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require brille24/sylius-customer-options-plugin:*" to figure out if any version is installable, or "composer require brille24/sylius-customer-options-plugin:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Can you help me to solve this?

KR
Micha

**Comment by mamazu** [comment]
Hey, thanks for reporting the issue. This plugin is not yet compatible with doctrine version 3. Looks like the plugin uses an outdated doctrine function that has been removed in 3.0.
 
More info: https://github.com/Brille24/SyliusCustomOptionsPlugin/issues/100

**Comment by MichaNeroucheff** [comment]
Did I need to install a old version of Sylius? like Sylius 1.12.0 ?

**Comment by mamazu** [comment]
Yes, it should work with older versions of Sylius. Preferably one that does not use doctrine version 3.

**Comment by mamazu** [comment]
This should be closed as of #132
