### ISSUE TITLE
DI Extension for Migrations messes up project migrations

### ISSUE THREAD

**Issue by JoppeDC** [Brille24/SyliusCustomOptionsPlugin#148]
The following DI extension should IMO not be included in this plugin:
https://github.com/Brille24/SyliusCustomOptionsPlugin/blob/master/src/DependencyInjection/Brille24SyliusCustomerOptionsExtension.php

This extension completely messes with the project migrations. Without any additional code and configuration, this will cause project migrations to generate in the vendor dir. Besides that, it will always load the bundle migrations, which shouldn't happen (these migratinos should be generated and run in the project itself). Besides that, the migrations included in the plugin also appear to be broken.

**Comment by mamazu** [comment]
Yes, this plugin still uses the old structure where the bundle generates the structure. The plugin needs to be updated. If you want to dig into that, I'd happily merge that.

This also ties into the xml to attribute migration. Sadly I have no experience with the migration.

**Comment by JoppeDC** [comment]
Hi @mamazu , I've updated the doctrine entities to use the newer attributes, and removed the old way of migrations. If you have the time, please have a look at the changes. We can continue the conversation on the PR thread.
