### ISSUE TITLE
CustomerOption targetEntity must be the CustomerOptionInterface on CustomerOptionTranslation Entity

### ISSUE THREAD

**Issue by mbutl** [Brille24/SyliusCustomOptionsPlugin#152]
To be able to add custom fields on CustomerOptionValue and CustomerOption entiies, i overwrite these classes and use the following doctrine configuration to use my new entities : 

```yaml
        resolve_target_entities:
            Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValueInterface: App\Entity\CustomerOption\CustomerOptionValue
            Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionInterface: App\Entity\CustomerOption\CustomerOption

```

However, for the CustomerOption, i have this error : 

```
[Doctrine\ORM\ORMInvalidArgumentException]                                                                                                                                                               
  Expected value of type "Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOption" for association field "Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionTr  
  anslation#$translatable", got "App\Entity\CustomerOption\CustomerOption" instead.
```

After checking join configuration in CustomerOptionTranslation entity, i see that: 

```php
#[ORM\ManyToOne(targetEntity: CustomerOption::class, inversedBy: 'translations')]
#[ORM\JoinColumn(onDelete: 'CASCADE')]
protected ?TranslatableInterface $translatable = null;
```

The CustomerOptionInterface must be used here 

```php
#[ORM\ManyToOne(targetEntity: CustomerOptionInterface::class, inversedBy: 'translations')]
#[ORM\JoinColumn(onDelete: 'CASCADE')]
protected ?TranslatableInterface $translatable = null;
```

**Comment by mamazu** [comment]
Hey thank you for reporting this bug. We haven't tested this use case. But if you have made it work with your setup like this feel free to create a pull request. I'd be happy to merge it.

**Comment by mamazu** [comment]
That's good to hear.
While working in the vendor directory is great for testing changes its a little tricky to push from there. Because by default composer clones this repository into the vendor directory (which you don't have write access to). What you would need to do is fork this repository, put the changes in the fork and then create a pull request from your fork to this repository.

If you need any further explanation feel free to say so.

**Comment by mbutl** [comment]
Thanks for the explanation.

There is the pull request https://github.com/Brille24/SyliusCustomOptionsPlugin/pull/153

**Comment by mamazu** [comment]
Closing this here as the PR is merged. If you still have issues with it feel free to open this again.
