### ISSUE TITLE
Handle annotations entity config

### ISSUE THREAD

**Issue by AxelDeneu** [Brille24/SyliusCustomOptionsPlugin#25]
I'm experiencing a bug after the migration.
It seems that the plugin doesn't handle the annotations for the entity config.
In my project I use annotations and this error is displaying : 
```
The association Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroup#products refers to the owning side field App\Entity\Product\Product#customerOptionGroup which does not exist.
```

Can you guys please help me ?

**Comment by AxelDeneu** [comment]
Okay I was able to make it work by manually adding annotations on the Product' override class : 
```
/**
 * @ORM\ManyToOne(targetEntity="Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionGroupInterface", inversedBy="products")
 * @ORM\JoinColumn(onDelete="SET NULL")
 */
protected $customerOptionGroup;

/**
 * @ORM\OneToMany(targetEntity="Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionValuePriceInterface", mappedBy="product", orphanRemoval=true, cascade={"persist", "remove"})
 */
protected $customerOptionValuePrices;
```

I don't close this issue because this is a temporary fix.

**Comment by AxelDeneu** [comment]
My bad, by default, Sylius create overriding classes in the src folder.
I was able to integrate the options by extending those overriding classes with the SyliusCustomOptionsPlugin classes. The classes to extend was "Product" and OrderItem.

Shoudl you add this disclaimer in the installation instructions ?

**Comment by mamazu** [comment]
The Customer Options plugin uses an XML configuration if you are using annotation you might need to define those when adding the trait to the `ProductVariant` class. But it would be great if you could add a section in the documentation about how to integrate the plugin with Annotation Mappings.

**Comment by AxelDeneu** [comment]
Yep I will au create a pull request with the updated documentation and I will add the French translations btw :)

**Comment by mamazu** [comment]
That would be great. Thanks.

**Comment by JakobTolkemit** [comment]
Since we're using traits to extend the core entities, we could just add annotations to them.

**Comment by mamazu** [comment]
That would also be an option.
