### ISSUE TITLE
Symfony Exception - TypeError

### ISSUE THREAD

**Issue by KirbyFox** [Brille24/SyliusCustomOptionsPlugin#26]
I get the following exception when visiting a Product page, after installing the plugin.

Argument 1 passed to Brille24\SyliusCustomerOptionsPlugin\Form\Extensions\AddToCartTypeExtension::getConstraints() must be an instance of Brille24\SyliusCustomerOptionsPlugin\Entity\ProductInterface, instance of App\Entity\Product\Product given

Sylius Version: 1.4.2
Symfony Version: 4.2.5

Any help would be greatly appreciated.

**Comment by JakobTolkemit** [comment]
Did you include the trait and interface provided by the plugin?

**Comment by KirbyFox** [comment]
There wasn't a `config/fixtures.yaml` file, so I created one and added the following, but it makes no differennce.

```
sylius_fixtures:
    suites:
        default: #Can be any suite you want
            fixtures:
                brille24_customer_option: #For Customer Options
                
                brille24_customer_option_group: #For Customer Option Groups
```

**Comment by KirbyFox** [comment]
When I go into `Admin` and then `Customer Option Groups`, it throws the following exception.

`An exception has been thrown during the rendering of a template ("Notice: Undefined index: customerOptionGroup").`

**Comment by JakobTolkemit** [comment]
Sylius 1.4 created overrides for the core entities in the `src/Entity` directory right?
What you need to do, is make your `Product` entity implement our `ProductCustomerOptionCapableTraitInterface` and use the `ProductCustomerOptionCapableTrait`.
Same with `OrderItem`.

Sorry this is not in the documentation yet.

**Comment by KirbyFox** [comment]
Thanks. I really want to use this plugin and believe in it, but without this vital piece of the documentation, it presents a real barrier to entry.

I tried your suggestion, but it's now throwing the following exception.

`Attempted to load interface "ProductInterface" from namespace "App\Entity\Product".`

**Comment by JakobTolkemit** [comment]
Could you tell me the steps to recreate that bug?
Then I can test it locally.

**Comment by KirbyFox** [comment]
I changed the code within `Entity/ProductVariant.php` to the following:

```
<?php

declare(strict_types=1);

namespace App\Entity\Product;

use Doctrine\ORM\Mapping\MappedSuperclass;
use Doctrine\ORM\Mapping\Table;
use Sylius\Component\Core\Model\ProductVariant as BaseProductVariant;
use Sylius\Component\Product\Model\ProductVariantTranslationInterface;
use Brille24\SyliusCustomerOptionsPlugin\Traits\ProductCustomerOptionCapableTrait;

/**
 * @MappedSuperclass
 * @Table(name="sylius_product_variant")
 */
class ProductVariant extends BaseProductVariant implements ProductInterface {
    use ProductCustomerOptionCapableTrait {
        __construct as protected customerOptionCapableConstructor;
    }

     public function __construct()
    {
        parent::__construct();

        $this->customerOptionCapableConstructor();
    }

    protected function createTranslation(): ProductVariantTranslationInterface
    {
        return new ProductVariantTranslation();
    }
}
```

**Comment by JakobTolkemit** [comment]
You shouldn't implement `ProductInterface` in `ProductVariant`.
I guess what you meant to do was implementing `ProductCustomerOptionCapableTraitInterface`

**Comment by KirbyFox** [comment]
Still no joy.

I'm beginning to wonder if this plugin actually works at all.

```
<?php

declare(strict_types=1);

namespace App\Entity\Product;

use Doctrine\ORM\Mapping\MappedSuperclass;
use Doctrine\ORM\Mapping\Table;
use Sylius\Component\Core\Model\ProductVariant as BaseProductVariant;
use Sylius\Component\Product\Model\ProductVariantTranslationInterface;
use Brille24\SyliusCustomerOptionsPlugin\Traits\ProductCustomerOptionCapableTrait;
use Brille24\SyliusCustomerOptionsPlugin\Traits\ProductCustomerOptionCapableTraitInterface;

/**
 * @MappedSuperclass
 * @Table(name="sylius_product_variant")
 */
class ProductVariant extends BaseProductVariant implements ProductCustomerOptionCapableTraitInterface {
    use ProductCustomerOptionCapableTrait {
        __construct as protected customerOptionCapableConstructor;
    }

     public function __construct()
    {
        parent::__construct();

        $this->customerOptionCapableConstructor();
    }

    protected function createTranslation(): ProductVariantTranslationInterface
    {
        return new ProductVariantTranslation();
    }
}

```

**Comment by KirbyFox** [comment]
Also.

```
<?php

declare(strict_types=1);

namespace App\Entity\Product;

use Doctrine\ORM\Mapping\MappedSuperclass;
use Doctrine\ORM\Mapping\Table;
use Sylius\Component\Core\Model\Product as BaseProduct;
use Sylius\Component\Product\Model\ProductTranslationInterface;
use Brille24\SyliusCustomerOptionsPlugin\Traits\ProductCustomerOptionCapableTrait;
use Brille24\SyliusCustomerOptionsPlugin\Traits\ProductCustomerOptionCapableTraitInterface;

/**
 * @MappedSuperclass
 * @Table(name="sylius_product")
 */
class Product extends BaseProduct
implements ProductCustomerOptionCapableTraitInterface {
     use ProductCustomerOptionCapableTrait {
         __construct as protected customerOptionCapableConstructor;
     }

      public function __construct()
     {
         parent::__construct();

         $this->customerOptionCapableConstructor();
     }

    protected function createTranslation(): ProductTranslationInterface
    {
        return new ProductTranslation();
    }
}

```

**Comment by mamazu** [comment]
The product needs to implement the `ProductInterface` from the plugin. This already takes care of the `ProductCustomerOptionsCapableTraitInterface`

**Comment by KirbyFox** [comment]
Thanks @mamazu 

I just tried your suggestion, but when visiting a Product page, it still throws the following exception.

`Argument 1 passed to Brille24\SyliusCustomerOptionsPlugin\Form\Extensions\AddToCartTypeExtension::getConstraints() must be an instance of Brille24\SyliusCustomerOptionsPlugin\Entity\ProductInterface, instance of App\Entity\Product\Product given`

**Comment by mamazu** [comment]
But the `App\Entity\Product\Product` entity should implement this interface.

**Comment by KirbyFox** [comment]
Thanks @mamazu 

I've tried changing `config/Entity/Product/Product.php `and `src/Entity/Product/Product.php`

I'm using the latest version of Sylius with the Symfony 4 directory structure.

**Comment by KirbyFox** [comment]
This looks wrong. 

`https://github.com/Brille24/SyliusCustomOptionsPlugin#generating-customer-options-with-fixtures
`
But this suggests that the file is called `fixtures.yml `not `fixtures.yaml`

`https://github.com/Sylius/Sylius/blob/master/src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures.yml`

**Comment by mamazu** [comment]
Both should work.

**Comment by KirbyFox** [comment]
Surely someone must have this plugin working within their project?

Is it compatible with the latest version of Sylius?

Could someone please post a copy of their `Entity/Product/Product.php` file?

I'm still getting the same error message and it's so frustrating, as I've followed the installation instructions.

`Argument 1 passed to Brille24\SyliusCustomerOptionsPlugin\Form\Extensions\AddToCartTypeExtension::getConstraints() must be an instance of Brille24\SyliusCustomerOptionsPlugin\Entity\ProductInterface, instance of App\Entity\Product\Product given `

**Comment by KirbyFox** [comment]
Also, when trying to access the `Products` section within `Admin`, it throws the following exception.

`An exception has been thrown during the rendering of a template ("Neither the property "customerOptionGroup" nor one of the methods "getCustomerOptionGroup()", "customerOptionGroup()", "isCustomerOptionGroup()", "hasCustomerOptionGroup()", "__get()" exist and have public access in class "App\Entity\Product\Product".").`

**Comment by mamazu** [comment]
This looks like the Product Entity you are using in Sylius still doesn't implement the `ProductInterface` from the Plugin because this would require the `getCustomerOptionsGroup()` to exist: 
https://github.com/Brille24/SyliusCustomOptionsPlugin/blob/573714cff3935a21a5d85193fe59564edee78e90/src/Traits/ProductCustomerOptionCapableTraitInterface.php#L25

**Comment by mamazu** [comment]
Did you also overrode the product entity of Sylius in your resource configuration?

**Comment by KirbyFox** [comment]
Thanks for your help @mamazu 

I completed the following step within the documentation.

In order to use the customer options, you need to override the product/product variant or whatever entity you want to price.

```
class Product implements ProductInterface {
    use ProductCustomerOptionCapableTrait {
        __construct as protected customerOptionCapableConstructor;
    }
    
     public function __construct()
    {
        parent::__construct();

        $this->customerOptionCapableConstructor();
    }
    // ...
}
```

But surely that won't include `getCustomerOptionsGroup()` etc.

**Comment by mamazu** [comment]
This sounds very odd. With the same code this runs in our shop perfectly well.
What PHP version are you using?

The idea behind this use statement is that it **only** aliases the `__construct` method with a new name and imports the rest of them without renaming. What you could try to do is explicitly also mention the other methods like so:
```php
use ProductCustomerOptionCapableTrait {
    __construct as protected customerOptionCapableConstructor;
    getCustomerOptionGroup as public getCustomerOptionGroup;
    // ...
}
```

**Comment by KirbyFox** [comment]
Thanks @mamazu but that results in the following exception:

`Compile Error: Trait method getCustomerOptionGroup has not been applied, because there are collisions with other trait methods on App\Entity\Product\Product`

**Comment by KirbyFox** [comment]
I'll have to look for another plugin as I've spent days wrestling with this one and I really don't think it's compatible with the latest version of Sylius, with the new Symfony 4 directory structure. Plus, there are obviously some important steps missing from the installation instructions.

It's a shame as I really wanted to use this one. Thanks for your help guys anyway.

**Comment by KirbyFox** [comment]
This

`In order to use the customer options, you need to override the product and order item.`

```
use Brille24\SyliusCustomerOptionsPlugin\Entity\ProductInterface;
use Brille24\SyliusCustomerOptionsPlugin\Traits\ProductCustomerOptionCapableTrait;

class Product extends BaseProduct implements ProductInterface {
    use ProductCustomerOptionCapableTrait {
        __construct as protected customerOptionCapableConstructor;
    }
    
     public function __construct()
    {
        parent::__construct();

        $this->customerOptionCapableConstructor();
    }
    // ...
}
```

Results in this...

`Class "App\Entity\Product\Product" sub class of "Sylius\Component\Core\Model\Product" is not a valid entity or mapped super class.`

**Comment by mamazu** [comment]
But there is a use Statement like this in your file?
`use Sylius\Component\Core\Model\Product as BaseProduct`

**Comment by KirbyFox** [comment]
```
<?php

declare(strict_types=1);

namespace App\Entity\Product;

use Brille24\SyliusCustomerOptionsPlugin\Entity\ProductInterface;
use Brille24\SyliusCustomerOptionsPlugin\Traits\ProductCustomerOptionCapableTrait;
use Doctrine\ORM\Mapping\MappedSuperclass;
use Doctrine\ORM\Mapping\Table;
use Sylius\Component\Core\Model\Product as BaseProduct;
use Sylius\Component\Product\Model\ProductTranslationInterface;

class Product extends BaseProduct implements ProductInterface {
    use ProductCustomerOptionCapableTrait {
        __construct as protected customerOptionCapableConstructor;
    }

     public function __construct()
    {
        parent::__construct();

        $this->customerOptionCapableConstructor();
    }

    protected function createTranslation(): ProductTranslationInterface
    {
        return new ProductTranslation();
    }
}
```
`
Class "App\Entity\Product\Product" sub class of "Sylius\Component\Core\Model\Product" is not a valid entity or mapped super class.`

**Comment by mamazu** [comment]
Have you defined an entity mapping for this class?

**Comment by KirbyFox** [comment]
Thanks @mamazu No, I simply followed the installation instructions and edited the s`rc/Entity/Product/Product.php `file that the latest version of Sylius provides as part of the installation.

The plugin installation instructions don't mention mapping.

**Comment by mamazu** [comment]
Yeah this plugin assumes that you already have overriden the entity and you only need to add the trait.

**Comment by KirbyFox** [comment]
The `config/packages/_sylius.yaml` file already contains all of the relevant mapping, so there's nothing to add there.

```
sylius_product:
    resources:
        product:
            classes:
                model: App\Entity\Product\Product
                repository: App\Repository\ProductRepository
            translation:
                classes:
                    model: App\Entity\Product\ProductTranslation
```

I really don't know what else to try now and I'm beginning to think that this plugin is just not compatible with the latest version of Sylius (1.4.2) which uses the Symfony 4 directory structure.

I really appreciate everyone's help, but I've wasted several days on trying to get this plugin working now.

**Comment by KirbyFox** [comment]
I've just got it working!!!!!!

`src/Entity/Product/Product.php` needed to be as follows:

```
<?php

declare(strict_types=1);

namespace App\Entity\Product;

use Brille24\SyliusCustomerOptionsPlugin\Entity\ProductInterface;
use Brille24\SyliusCustomerOptionsPlugin\Traits\ProductCustomerOptionCapableTrait;
use Doctrine\ORM\Mapping\MappedSuperclass;
use Doctrine\ORM\Mapping\Table;
use Sylius\Component\Core\Model\Product as BaseProduct;
use Sylius\Component\Product\Model\ProductTranslationInterface;

/**
 * @MappedSuperclass
 * @Table(name="sylius_product")
 */
class Product extends BaseProduct implements ProductInterface {
    use ProductCustomerOptionCapableTrait {
        __construct as protected customerOptionCapableConstructor;
    }

     public function __construct()
    {
        parent::__construct();

        $this->customerOptionCapableConstructor();
    }

    protected function createTranslation(): ProductTranslationInterface
    {
        return new ProductTranslation();
    }
}
```

Thank you so much to everyone who helped.

**Comment by mamazu** [comment]
What was the final solution?

**Comment by KirbyFox** [comment]
@mamazu It was literally to change `src/Entity/Product/Product.php` to the code that I included above.

I just have one remaininng issue.

When editing a product within Admin, it throws the following exception:

`Return value of App\Entity\Product\Product::getCustomerOptionValuePrices() must implement interface Doctrine\Common\Collections\Collection, null returned`

**Comment by mamazu** [comment]
Can you verify that the `ProductCustomerOptionCapableTrait` constructor is called? There it defines the `customerOptionValuePrices` to be an `ArrayCollection`.

**Comment by KirbyFox** [comment]
Thanks @mamazu I'm not sure where I need to look to see if the `ProductCustomerOptionCapableTrait` constructor is called.

I've looked in `Symfony Profiler` and can't immediately find a reference to it.

I've just got this one remaining problem now, but as it is, not products can be edited anymore.

**Comment by mamazu** [comment]
Just go into the traits constructor method and add something like this
```php
var_dump('testing');
die();
```
If it shows this text then the method is called. If not then this method is not called.

**Comment by KirbyFox** [comment]
I assume you're referring to the file `vendor/brille24/sylius-customer-options-plugin/src/Traits/ProductCustomerOptionCapableTraitInterface.php`

If so, I can't find the constructor.

**Comment by mamazu** [comment]
Not the interface the actual trait.

**Comment by KirbyFox** [comment]
Sorry, I've just added your code to the `__construct()` function within the `vendor/brille24/sylius-customer-options-plugin/src/Traits/ProductCustomerOptionCapableTrait.php` file and the text wasn't displayed.

So I guess it's not being called.

**Comment by mamazu** [comment]
Can you try to reinstall the plugin in the latest version?

**Comment by KirbyFox** [comment]
Tanks @mamazu I've just done that and cleared the cache, but it still throws the following exception when editing a `Product `with `Admin`.

`Return value of App\Entity\Product\Product::getCustomerOptionValuePrices() must implement interface Doctrine\Common\Collections\Collection, null returned`

The `Product `pages on the 'public' side are working perfectly.

**Comment by KirbyFox** [comment]
Below the exception, at the top of the Stack Trace are the following lines:

`in vendor/brille24/sylius-customer-options-plugin/src/Traits/ProductCustomerOptionCapableTrait.php (line 73) `

`in vendor/symfony/property-access/PropertyAccessor.php->getCustomerOptionValuePrices (line 372) `

**Comment by KirbyFox** [comment]
I've added a `Hack` as follows, which has at least stopped the error message and allows the Edit Product page to open.

`vendor/brille24/sylius-customer-options-plugin/src/Traits/ProductCustomerOptionCapableTrait.php (line 68).`

    /**
     * {@inheritdoc}
     */
    public function getCustomerOptionValuePrices(): Collection
    {
        if ($this->customerOptionValuePrices == null){
          $this->customerOptionValuePrices = new ArrayCollection();
        }

        return $this->customerOptionValuePrices;
    }

**Comment by KirbyFox** [comment]
Now it throws an exception when you click on `Customer Option Groups` within Admin.

`An exception has been thrown during the rendering of a template ("Notice: Undefined index: customerOptionGroup").`

 `vendor/sylius/sylius/src/Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig (line 78) `

**Comment by mamazu** [comment]
I'll try to install it into a clean Sylius and note down the steps as I go and see if I can reproduce the errors you are reporting.

**Comment by KirbyFox** [comment]
Hi @mamazu Thanks, that would be really helpful and I'm sure it will lead to improvements to the plugin and/or documentation. Please use the very latest version of Sylius, with the Symfony 4 directory structure.

Many thanks for this.

**Comment by mamazu** [comment]
Just did, couldn't find any problem except that the translation update command does not work. But this is not important in this case. You can have a look at the source code here:
https://drive.google.com/file/d/1-8UoKkLSKYvHoo_He-cXcmo7HUZUOVkW/view?usp=sharing

**Comment by KirbyFox** [comment]
Thanks @mamazu 

I copied your version (unchanged) and it's still throwing all the same errors.

e.g. When editing a product - 

`Return value of App\Entity\Product\Product::getCustomerOptionValuePrices() must implement interface Doctrine\Common\Collections\Collection, null returned`

**Comment by mamazu** [comment]
Have you tried to clear the cache? Or have done any other configuration changes? Because it works on my machine.

**Comment by KirbyFox** [comment]
Hi @mamazu The only things I did was clear the cache and run `composer update`. Other than that it was simply copied and pasted from your zip file.

Thanks.

**Comment by mamazu** [comment]
Hm, to be honest I have no idea what is different with your setup. One last thing that you can try is delete the `var/cache` folder. If that doesn't solve the problem, I am out of ideas.

**Comment by KirbyFox** [comment]
Thanks @mamazu Yes, I'm out of ideas now too. Yes, deleting the `var/cache/dev` folder is what I did.

I'm running PHP Version 7.2.7.

Thanks again for your help and I hope that other users of your plugin have better luck than I did.

**Comment by mamazu** [comment]
Thanks for trying though.
