### ISSUE TITLE
Type Error in AddToCartTypeExtension

### ISSUE THREAD

**Issue by parthajudiyap** [Brille24/SyliusCustomOptionsPlugin#31]
Argument 1 passed to Brille24\SyliusCustomerOptionsPlugin\Form\Extensions\AddToCartTypeExtension::getConstraints() must be an instance of Brille24\SyliusCustomerOptionsPlugin\Entity\ProductInterface, instance of App\Entity\Product\Product given, called in

https://ibb.co/MkFYVqP

**Comment by mamazu** [comment]
Does your `Product` implement the `ProductInterface`?

**Comment by mamazu** [comment]
@parthajudiyap Any update?
