### ISSUE TITLE
Viewing customer option groups table

### ISSUE THREAD

**Issue by mamazu** [Brille24/SyliusCustomOptionsPlugin#35]
When you create a customer option and you call the backend to display the customer options in a table, the rendering throws an exception: `Notice: undefined exception customerOptionGroup` for the `Sylius/Bundle/UiBundle/Resources/views/Grid/_default.html.twig`

**Comment by JakobTolkemit** [comment]
This is caused by doctrine ignoring the mapping information provided in our traits.

Related: https://github.com/Sylius/Sylius-Standard/issues/332
