### ISSUE TITLE
Option dependent price

### ISSUE THREAD

**Issue by jaapio** [Brille24/SyliusCustomOptionsPlugin#37]
Hi,

Thanks for the awesome plugin! It works very nice. 
The only missing feature from our point of view is a price that depends on other options. 

So for example, when a customer selects that he wants a type of addition the price of another option changes. 

I tried to accomplish this with a custom price caluclator but that didn't work since I didn't have the right information in the price calculator. 

Do you know a way that could help us out?

Jaap

**Comment by mamazu** [comment]
Hello and thank you for using our plugin,
the task you are trying to accomplish sounds quite complicated configuration wise. To recall:
Let's suppose you are selling t-shirts with different colors and the option to add text. What you are trying to achieve would be changing the price of the text on the t-shirt based on the color of the shirt. Am I understanding that correctly?

One easy thing you could do would be to change the `OrderPricesCalculator` which is located here:
https://github.com/Brille24/SyliusCustomOptionsPlugin/blob/master/src/Services/OrderPricesRecalculator.php
There you can take all the customer options into account and do your own price calculation logic.

**Comment by jaapio** [comment]
We are selling an installation pack for satellite internet.
When people choose to rent the hardware they will get a discount. The amount of discount is based on the type of hardware the choose. 
Let's say if the choose rental, when they selected the home installation pack, the get a discount of 300 euro. If they have chosen for the professional pack they get a discount of 375.

I will try to give the OrderPricesRecalculator a shot. Thanks in advance.

**Comment by jaapio** [comment]
Thanks for the suggestion. I made it work with your hint towards the OrderPricesRecalculator. 

In the services.yml
```
    App\Services\OrderPriceRecalculator:
        decorates: brille24.customer_options_plugin.services.order_prices_recalculator
        arguments: ['@App\Services\OrderPriceRecalculator.inner']
        tags: ['sylius.order_processor']
```

The actual class:

```
<?php

declare(strict_types=1);

namespace App\Services;

use Brille24\SyliusCustomerOptionsPlugin\Entity\OrderItemInterface;
use Sylius\Component\Order\Model\OrderInterface;
use Sylius\Component\Order\Processor\OrderProcessorInterface;

final class OrderPriceRecalculator implements OrderProcessorInterface
{
    /**
     * @var OrderProcessorInterface
     */
    private $orderProcessor;

    public function __construct(OrderProcessorInterface $orderProcessor)
    {
        $this->orderProcessor = $orderProcessor;
    }

    /**
     * @param OrderInterface $order
     */
    public function process(OrderInterface $order): void
    {
        $this->orderProcessor->process($order);
        foreach ($order->getItems() as $orderItem) {
            if (!$orderItem instanceof OrderItemInterface) {
                continue;
            }


            $options = $orderItem->getCustomerOptionConfiguration(true);
            if (array_key_exists('MODEM', $options) && array_key_exists('INSTALL_PACK', $options)) {
                if ($options['MODEM']->getCustomerOptionValueCode() === 'RENTAL') {
                    switch ($options['INSTALL_PACK']->getCustomerOptionValueCode()) {
                        case 'HOME_ROUTER':
                            $options['MODEM']->setFixedPrice(-50000);
                            break;
                        case 'PRO_ROUTER':
                            $options['MODEM']->setFixedPrice(-55500);
                            break;
                        case 'NO_ROUTER':
                        default:
                            break;

                    }
                }
            }
        }
    }
}
```
It feels a bit uncomfortable to have the prices hard coded but we will find a way to fix that.

**Comment by mamazu** [comment]
Yeah, as I said making it configurable would be quite a nightmare because you would have to have a lot of options. But looks good (you could extract that into a service)
