### ISSUE TITLE
No works Adding product/order item To Cart

### ISSUE THREAD

**Issue by locos973** [Brille24/SyliusCustomOptionsPlugin#39]
Hello, following the installation of the bundle Brille24/SyliusCustomOptionsPlugin

When adding products to the cart. I can't add 2 different products, automatically when adding the second product to the cart it adds a quantity on the first product. 
Would anyone have this problem?
My products for the testing doesn't have a CustomOptions. They are basic product, one with a variants and one without variants.
When I disable the bundle, everything comes back to normal.
I doesn't have any errors in log

**Comment by locos973** [comment]
Ok it's ok now, i know why. We need to add customer Group Option for all my products else it's a bug.
![image](https://user-images.githubusercontent.com/22006991/61350896-5efa3880-a869-11e9-98b2-9d3d304944a9.png)

So i create a "Empty" CustomerOptionGroup and adding this default CustomerOptionGroup for all my products without customOption . 
I solve my problems. 
Thanks for this bundle, it's amazing

**Comment by JakobTolkemit** [comment]
Reopening this, as it should not be mandatory to assign a customer option group to every product.

**Comment by mamazu** [comment]
I have tried to fix it and noticed that items are always equals to anything if the module is enabled but no resource overrides happen. I added a unit test for this case as well. I don't know if this fixes your issue, could you pull the latest version and try again? @locos973

**Comment by locos973** [comment]
All right, you have fixed this issue. I have tried with your last commit #721fa6e 
Thanks @mamazu

**Comment by mamazu** [comment]
Okay, then I will close this issue. Thanks for reporting it.
