### ISSUE TITLE
Migrations files for v1.6.0 - 404: Not Found

### ISSUE THREAD

**Issue by ghost** [Brille24/SyliusCustomOptionsPlugin#43]
Hello,

I'm using the Sylius 1.6.0.
I was trying to solve the admin product option client form, because there's no `Customer option value`  in the list form :
![image](https://user-images.githubusercontent.com/7100248/69814156-e7afba80-11f3-11ea-95b6-7ac16a3f0310.png)

And I saw an update, I was thinking it's maybe this. But I can't complete the installation process from : https://github.com/Brille24/SyliusCustomOptionsPlugin/blob/master/UPGRADE-1.6.md

But the migrations files are missing. 
Could you please give us a new link ?
Are you able to give me any information in order to fix the creation of customer options values on a product ?

Thanks

**Comment by mamazu** [comment]
You can just run the migration command anyways, but this should not be the problem you are facing if the list is empty you might be missing something else.

**Comment by mamazu** [comment]
The correct file would be https://github.com/Brille24/SyliusCustomOptionsPlugin/blob/master/tests/Application/src/Migrations/Version20191010092727.php
