### ISSUE TITLE
master is ahead of 2.4 tag

### ISSUE THREAD

**Issue by davidpeoples** [Brille24/SyliusCustomOptionsPlugin#49]
I don't know if this is intentional, but the latest tag (2.4) is behind master by one commit. This has the effect of being unable to install this plugin with Sylius 1.7 with the published instructions, because the 2.4 tagged branch still has the exclude instruction for 1.7 in its composer.json file. I worked around it for now by forcing composer to install the master branch.

**Comment by mamazu** [comment]
Currently this module is not tested for 1.7 that's why its not tagged. But it will be in the near future.

**Comment by davidpeoples** [comment]
Thanks. I did see some other problems after completing the installation. I'm not experienced with Sylius enough yet to be sure it isn't just some other thing I've broken or don't understand, so no more issues from me yet. I'll try with Sylius 1.6 first.

**Comment by mamazu** [comment]
I mean it would be great if you could add a proper 1.7 support. But other than that thanks for using the plugin. :)
