### ISSUE TITLE
Compatibility with Sylius 1.7 

### ISSUE THREAD

**Issue by atapatel** [Brille24/SyliusCustomOptionsPlugin#53]
Hello can you guys tell me how can I install it with latest Sylius version 1.7 ?

**Comment by mamazu** [comment]
You should just be able to install it with `composer require brille24/brille24/sylius-customer-options-plugin`. If you run into problems with some packages not working please add a screen shot or a dump of your conflicts. (The CI is currently not working so it might be buggy).

**Comment by atapatel** [comment]
composer require brille24/sylius-customer-options-plugin
Using version ^2.4 for brille24/sylius-customer-options-plugin
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - brille24/sylius-customer-options-plugin 2.4 requires sylius/sylius ^1.6 -> satisfiable by sylius/sylius[v1.7.6, v1.7.0, v1.7.1, v1.7.2, v1.7.3, v1.7.4, v1.7.5].
    - brille24/sylius-customer-options-plugin 2.4 conflicts with sylius/sylius[v1.7.0].
    - brille24/sylius-customer-options-plugin 2.4 conflicts with sylius/sylius[v1.7.1].
    - brille24/sylius-customer-options-plugin 2.4 conflicts with sylius/sylius[v1.7.2].
    - brille24/sylius-customer-options-plugin 2.4 conflicts with sylius/sylius[v1.7.3].
    - brille24/sylius-customer-options-plugin 2.4 conflicts with sylius/sylius[v1.7.4].
    - brille24/sylius-customer-options-plugin 2.4 conflicts with sylius/sylius[v1.7.5].
    - brille24/sylius-customer-options-plugin 2.4 conflicts with sylius/sylius[v1.7.6].
    - brille24/sylius-customer-options-plugin 2.4 conflicts with sylius/sylius[v1.7.6].
    - brille24/sylius-customer-options-plugin 2.4 conflicts with sylius/sylius[v1.7.6].
    - Installation request for brille24/sylius-customer-options-plugin ^2.4 -> satisfiable by brille24/sylius-customer-options-plugin[2.4].


Installation failed, reverting ./composer.json to its original content.

**Comment by mamazu** [comment]
Apparently this plugin is not compatible with Sylius 1.7 yet.

**Comment by moussaclarke** [comment]
@mamazu Do you know what changes might be needed to make it compatible with 1.7?

**Comment by mamazu** [comment]
Yes, we are using some sonata bundles that Sylius removed in 1.7.

**Comment by mamazu** [comment]
We will be upgrading to Sylius 1.7 with production in a few weeks so we will probably upgrade the plugin too.

**Comment by antiseptikk** [comment]
For the moment you can try to add `"brille24/sylius-customer-options-plugin": "dev-master as 2.4",` in your composer.json

**Comment by euperia** [comment]
I've installed this on a 1.7.6 site using the repository pin as mentioned above (https://github.com/Brille24/SyliusCustomOptionsPlugin/issues/53#issuecomment-654282992).

There are a couple of issues with the admin area and with the checkout pages.  Should I wait until a 1.7 release or would you like the issues reporting?

**Comment by mamazu** [comment]
Please feel free to report the issues. Then we will know what the stuff is we need to fix when migrating the plugin.

**Comment by mamazu** [comment]
It should be compatible with 1.7 (we have it in production with Sylius 1.7).
Closing now, if there are any other bug please open new ticket.s
