### ISSUE TITLE
There is no extension able to load the configuration for "brille24_customer_options"

### ISSUE THREAD

**Issue by maikelreyes** [Brille24/SyliusCustomOptionsPlugin#55]
Setting up this plugin I'm getting the following error:
There is no extension able to load the configuration for "brille24_customer_options" (in "D:\xampp\htdocs\storewallet\config/packages/routing.yaml"). Looked for namespace "brille24_customer_options", found ""framework", "monolog", "security", "swiftmailer", "twig", "doctrine", "doctrine_cache", "sylius_order", "sylius_money", "sylius_currency", "sylius_locale", "sylius_product", "sylius_channel", "sylius_attribute", "sylius_taxation", "sylius_shipping", "sylius_payment", "sylius_mailer", "sylius_promotion", "sylius_addressing", "sylius_inventory", "sylius_taxonomy", "sylius_user", "sylius_customer", "sylius_ui", "sylius_review", "sylius_core", "sylius_resource", "sylius_grid", "winzou_state_machine", "sonata_core", "sonata_block", "sonata_intl", "bazinga_hateoas", "jms_serializer", "fos_rest", "knp_gaufrette", "knp_menu", "liip_imagine", "payum", "stof_doctrine_extensions", "white_october_pagerfanta", "doctrine_migrations", "doctrine_fixtures", "sylius_fixtures", "sylius_payum", "sylius_theme", "sylius_admin", "sylius_shop", "fos_oauth_server", "sylius_admin_api", "debug", "web_profiler", "fidry_alice_data_fixtures", "nelmio_alice", "maker", "brille24_sylius_customer_options"" in D:\xampp\htdocs\storewallet\config/packages/routing.yaml (which is loaded in resource "D:\xampp\htdocs\storewallet\config/packages/routing.yaml").

Using Sylius 1.6 under PHP 7.2

**Comment by JakobTolkemit** [comment]
This looks like you put the routing.yaml in the wrong directory.
It should be in `config/routes`.
