### ISSUE TITLE
Feature Request: Show custom option only if specific core option value chosen

### ISSUE THREAD

**Issue by euperia** [Brille24/SyliusCustomOptionsPlugin#60]
This plugin is really nice.  Great work!

One feature I'd like to see is the ability to only show the custom option if the user chooses a value from another core option.

For example:

* There is a core/Sylius option of 'Colour' containing 'White, Red, Custom'. 
* A Custom Option called `custom_colour` is created but not a required field.
* When the user visits the product, the `custom_colour` isn't shown.
* If the user chooses 'White' from the Colours option, `custom_colour` isn't shown.
* If the user chooses 'Custom' from the Colours option, `custom_colour IS shown and is required before the item can be purchased.

**Comment by mamazu** [comment]
Thanks for using the plugin.

I don't really get your use case. You want to basically say if the user doesn't like one of the predefined options / variants in the shop they should be able to choose / create their own?

**Comment by euperia** [comment]
Yes :)

The site we're building has a product which is available in a range of popular colours but they can also make the product bespoke in any colour.

**Comment by mamazu** [comment]
That's an interesting use case and a valid point. We didn't consider that when developing it. If you want to try to implement it feel free to.

One possible implementation is to hide the Options from Sylius and then make some magic in the background that does variant magic. Other than that is only a frontend thing that you mark and hide the fields in the Frontend.

**Comment by euperia** [comment]
> That's an interesting use case and a valid point. We didn't consider that when developing it. If you want to try to implement it feel free to.
> 
> One possible implementation is to hide the Options from Sylius and then make some magic in the background that does variant magic. Other than that is only a frontend thing that you mark and hide the fields in the Frontend.

Thats _exactly_ what we're doing 👍

**Comment by mamazu** [comment]
Sounds great. If you already have a working version I'd be happy to help you with a merge request. :)
