### ISSUE TITLE
Required option does not work

### ISSUE THREAD

**Issue by dominx99** [Brille24/SyliusCustomOptionsPlugin#74]
```Version: 2.7.6```

I set an option required on the admin side and on the frontend there is a red * next to the label, but I can add product to the cart without selecting any report.

-------

![image](https://user-images.githubusercontent.com/25711467/107354228-32061a00-6ace-11eb-904e-8909b346705b.png)
![image](https://user-images.githubusercontent.com/25711467/107354250-39c5be80-6ace-11eb-9693-2d884d882962.png)

**Comment by mamazu** [comment]
Thanks for reporting the bug I will have a look at it this evening.

**Comment by mamazu** [comment]
Yeah the reason for this is required only works for text fields for multiselect fields you have to have a minimum amount of options selected. This is related to this issue:
https://github.com/Brille24/SyliusCustomOptionsPlugin/issues/17

**Comment by mamazu** [comment]
I found that this is actually a bug. It is fixed in the latest version of the package.
