### ISSUE TITLE
Argument 1 passed to Brille24\SyliusCustomerOptionsPlugin\Entity\CustomerOptions\CustomerOptionAssociation::setPosition() must be of the type int, null given

### ISSUE THREAD

**Issue by DieterHolvoet** [Brille24/SyliusCustomOptionsPlugin#78]
There's something wrong with the form validation of customer option groups. The option position field looks required, but when you leave it empty and submit the form an exception appears. I was able to work around the issue by removing the `int` type hint from the setter, but I understand that's probably not the real fix.

## Steps to reproduce
1. Add a new customer option group
2. Fill in all required fields and add one option, but leave the position field empty
3. Submit the form

**Comment by mamazu** [comment]
Thanks for reporting the bug I will try to look into it this evening.

**Comment by mamazu** [comment]
Yes, this looks like a bug. But I mean that shouldn't be empty. As far as I know that value, should be set with Javascript.

**Comment by DieterHolvoet** [comment]
Where can I find the Javascript that is supposed to set this value? Is it this file: [customerOptionFunctions.js](https://github.com/Brille24/SyliusCustomOptionsPlugin/blob/master/src/Resources/public/js/customerOptionFunctions.js)?

**Comment by mamazu** [comment]
Should be fixed in the new version. There was no Javascript but the default value of the position was null (which is not allowed as value.)

**Comment by DieterHolvoet** [comment]
Great, thanks a lot for your effort!

**Comment by mamazu** [comment]
No problem. If the issue shows up again feel free to reopen it.
