### ISSUE TITLE
renderPrice macro displays percent values incorrectly

### ISSUE THREAD

**Issue by seizan8** [Brille24/SyliusCustomOptionsPlugin#82]
The renderPrice macro in all/_orderItem.html.twig displays the percentage like:
( {{ orderItem.percent }} % )

So, if the value is 0.05 it's displayed as 0.05%, when it actually should be 5%. The percentages are correct in the form of the product show page though.
The percent should be multiplied by 100.

**Comment by mamazu** [comment]
Thanks for reporting this bug. It will be fixed in the next version.

**Comment by mamazu** [comment]
This is fixed in 2.11.2
