### ISSUE TITLE
Deprecated namespaces formats

### ISSUE THREAD

**Issue by sylfrid** [Brille24/SyliusCustomOptionsPlugin#87]
Hello. The plugin still has somes deprecated templates namespace formats with colons (like `SyliusUiBundle:Grid/Field:rawLabel.html.twig` instead of `@SyliusUi/Grid/Field/rawLabel.html.twig`).
It throws exceptions with SF5. I'll submit a new PR this week for that.

**Comment by mamazu** [comment]
I think this should be solved as the merge request is merged right?

**Comment by mamazu** [comment]
Ah good luck with that. Feel free to open more issues and merge requests if you encounter any other problems.
