### ISSUE TITLE
Why documentation is using bin/console doctrine:schema:update --force ?

### ISSUE THREAD

**Issue by bellu** [Brille24/SyliusCustomOptionsPlugin#99]
Hi,

i think the schema update should use `php bin/console doctrine:migrations:migrate`, or at the least this should be mentioned in the documentation.
Using `php bin/console doctrine:schema:update --force` could give errors in future migrations in the project.

**Comment by mamazu** [comment]
Hello thanks for pointing out this error out. This is correct. We should update the documentation as we also started to generate migrations as well.

**Comment by mamazu** [comment]
Updated the documentation to use migrations. If you have any other questions about the database migrations feel free to open the ticket back up.
